### ISSUE TITLE
`sudo pip command not found ECS base image`

### ISSUE THREAD

**Issue by jchannon** [hashicorp/terraform-aws-consul#53]
Hi, 

I've been trying to get this module running on a base AMI of the ECS image with packer:

```
source_ami_filter: 
      filters:
        virtualization-type: "hvm"
        architecture: "x86_64"
        name: "*-amazon-ecs-optimized"
        root-device-type: "ebs"
      owners: ["amazon"]
      most_recent: true
```
However when i get to `install-consul` it errors with `sudo pip command not found`

To overcome that I installed pip - ` - "sudo easy_install pip"`

I can run `pip -V` and I get a version out but `sudo pip -V` and I get `sudo pip command not found`

I can't tell if this an issue with the base ECS image or if the code in this module shouldn't call sudo on pip

Any pointers gratefully received 😄
